"""update

Revision ID: 18e8f5799b10
Revises: b0535fe5df94
Create Date: 2024-01-09 11:49:20.050348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e8f5799b10'
down_revision = 'b0535fe5df94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bgmVolume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sfxVolume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('narrationVolume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('forcedPowerUpKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('weaponQuickKey1', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('weaponQuickKey2', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('weaponQuickKey3', sa.String(length=1), nullable=True))
        batch_op.drop_column('volumeSetting')
        batch_op.drop_column('boomerangKey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boomerangKey', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('volumeSetting', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('weaponQuickKey3')
        batch_op.drop_column('weaponQuickKey2')
        batch_op.drop_column('weaponQuickKey1')
        batch_op.drop_column('forcedPowerUpKey')
        batch_op.drop_column('narrationVolume')
        batch_op.drop_column('sfxVolume')
        batch_op.drop_column('bgmVolume')

    # ### end Alembic commands ###
