"""migration to fit new fields

Revision ID: 3df6e6921503
Revises: c40a59b362b0
Create Date: 2023-12-17 15:16:10.110482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3df6e6921503'
down_revision = 'c40a59b362b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isGameOver', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('skellyDeaths', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enemiesKilled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damageDone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damageTaken', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('heavyAttacksUsed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lightAttacksUsed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dashesUsed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distanceTraveled', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('timeElapsed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mementosCollected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('levelReached', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upgradesMilkCollected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('skullHammerPickedUpJoe', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ribberanPickedUpJane', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('boneSwordFabulaPickedUp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('weaponEquipped', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currentLevel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('playerXPosition', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('playerYPosition', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('playerZPosition', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('healthAtSaveTime', sa.Integer(), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('healthAtSaveTime')
        batch_op.drop_column('playerZPosition')
        batch_op.drop_column('playerYPosition')
        batch_op.drop_column('playerXPosition')
        batch_op.drop_column('currentLevel')
        batch_op.drop_column('weaponEquipped')
        batch_op.drop_column('boneSwordFabulaPickedUp')
        batch_op.drop_column('ribberanPickedUpJane')
        batch_op.drop_column('skullHammerPickedUpJoe')
        batch_op.drop_column('upgradesMilkCollected')
        batch_op.drop_column('levelReached')
        batch_op.drop_column('mementosCollected')
        batch_op.drop_column('timeElapsed')
        batch_op.drop_column('distanceTraveled')
        batch_op.drop_column('dashesUsed')
        batch_op.drop_column('lightAttacksUsed')
        batch_op.drop_column('heavyAttacksUsed')
        batch_op.drop_column('damageTaken')
        batch_op.drop_column('damageDone')
        batch_op.drop_column('enemiesKilled')
        batch_op.drop_column('skellyDeaths')
        batch_op.drop_column('isGameOver')

    # ### end Alembic commands ###
