"""new db

Revision ID: 3ed830ebc1b1
Revises: ac6587298c05
Create Date: 2023-12-22 16:40:03.244754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed830ebc1b1'
down_revision = 'ac6587298c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endless_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('enemiesKilled', sa.Integer(), nullable=True),
    sa.Column('runScore', sa.Integer(), nullable=True),
    sa.Column('damageDone', sa.Integer(), nullable=True),
    sa.Column('damageTaken', sa.Integer(), nullable=True),
    sa.Column('heavyAttacksUsed', sa.Integer(), nullable=True),
    sa.Column('lightAttacksUsed', sa.Integer(), nullable=True),
    sa.Column('dashesUsed', sa.Integer(), nullable=True),
    sa.Column('distanceTraveled', sa.Float(), nullable=True),
    sa.Column('timeElapsed', sa.Float(), nullable=True),
    sa.Column('regularMilkCollected', sa.Integer(), nullable=True),
    sa.Column('chocolateMilkCollected', sa.Integer(), nullable=True),
    sa.Column('coconutMilkCollected', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user_stats.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regularMilkCollected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chocolateMilkCollected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('coconutMilkCollected', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalRegularMilkCollected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalChocolateMilkCollected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalCoconutMilkCollected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cameraSensitivity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('volumeSetting', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('forwardKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('backwardKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('leftKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('rightKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('dashKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('lightAttackKey', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('heavyAttackKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('powerUpKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('weaponToggleKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('boomerangKey', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('textSkipKey', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_column('textSkipKey')
        batch_op.drop_column('boomerangKey')
        batch_op.drop_column('weaponToggleKey')
        batch_op.drop_column('powerUpKey')
        batch_op.drop_column('heavyAttackKey')
        batch_op.drop_column('lightAttackKey')
        batch_op.drop_column('dashKey')
        batch_op.drop_column('rightKey')
        batch_op.drop_column('leftKey')
        batch_op.drop_column('backwardKey')
        batch_op.drop_column('forwardKey')
        batch_op.drop_column('volumeSetting')
        batch_op.drop_column('cameraSensitivity')
        batch_op.drop_column('totalCoconutMilkCollected')
        batch_op.drop_column('totalChocolateMilkCollected')
        batch_op.drop_column('totalRegularMilkCollected')

    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_column('coconutMilkCollected')
        batch_op.drop_column('chocolateMilkCollected')
        batch_op.drop_column('regularMilkCollected')

    op.drop_table('endless_game_stats')
    # ### end Alembic commands ###
