"""empty message

Revision ID: 8a3b7103f72e
Revises: 1a7ed54f0040
Create Date: 2023-11-28 18:23:44.466321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3b7103f72e'
down_revision = '1a7ed54f0040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('time_played',
                          existing_type=sa.Integer(),
                          type_=sa.Interval(),
                          existing_nullable=True,
                          postgresql_using='time_played * INTERVAL \'1 second\'')
        batch_op.drop_constraint('player_email_key', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('player_email_key', ['email'])
        batch_op.alter_column('time_played',
               existing_type=sa.Interval(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    op.drop_table('number_entry')
    # ### end Alembic commands ###
