"""migration to hanlde user

Revision ID: ac6587298c05
Revises: 3df6e6921503
Create Date: 2023-12-19 12:09:14.020119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6587298c05'
down_revision = '3df6e6921503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('mementosCollected', sa.Integer(), nullable=True),
    sa.Column('upgradesMilkCollected', sa.Integer(), nullable=True),
    sa.Column('levelReached', sa.Integer(), nullable=True),
    sa.Column('weaponEquipped', sa.Integer(), nullable=True),
    sa.Column('skullHammerPickedUpJoe', sa.Boolean(), nullable=True),
    sa.Column('ribberanPickedUpJane', sa.Boolean(), nullable=True),
    sa.Column('boneSwordFabulaPickedUp', sa.Boolean(), nullable=True),
    sa.Column('highScore', sa.Integer(), nullable=True),
    sa.Column('totalSkellyDeaths', sa.Integer(), nullable=True),
    sa.Column('totalEnemiesKilled', sa.Integer(), nullable=True),
    sa.Column('totalDamageDone', sa.Integer(), nullable=True),
    sa.Column('totalDamageTaken', sa.Integer(), nullable=True),
    sa.Column('totalHeavyAttacksUsed', sa.Integer(), nullable=True),
    sa.Column('totalLightAttacksUsed', sa.Integer(), nullable=True),
    sa.Column('totalDashesUsed', sa.Integer(), nullable=True),
    sa.Column('totalDistanceTraveled', sa.Float(), nullable=True),
    sa.Column('totalTimePlayed', sa.Float(), nullable=True),
    sa.Column('totalQuestsCompleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'user_stats', ['username'], ['username'])
        batch_op.drop_column('boneSwordFabulaPickedUp')
        batch_op.drop_column('weaponEquipped')
        batch_op.drop_column('mementosCollected')
        batch_op.drop_column('ribberanPickedUpJane')
        batch_op.drop_column('upgradesMilkCollected')
        batch_op.drop_column('levelReached')
        batch_op.drop_column('skullHammerPickedUpJoe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skullHammerPickedUpJoe', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('levelReached', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upgradesMilkCollected', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ribberanPickedUpJane', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mementosCollected', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weaponEquipped', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('boneSwordFabulaPickedUp', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('username')

    op.drop_table('user_stats')
    # ### end Alembic commands ###
