"""test

Revision ID: b0535fe5df94
Revises: 3ed830ebc1b1
Create Date: 2023-12-23 19:17:27.785431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0535fe5df94'
down_revision = '3ed830ebc1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endless_game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boomerangsUsed', sa.Integer(), nullable=True))

    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boomerangsUsed', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('QuestsCompleted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totalBoomerangsUsed', sa.Integer(), nullable=True))
        batch_op.drop_column('upgradesMilkCollected')
        batch_op.drop_column('totalQuestsCompleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalQuestsCompleted', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('upgradesMilkCollected', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('totalBoomerangsUsed')
        batch_op.drop_column('QuestsCompleted')

    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_column('boomerangsUsed')

    with op.batch_alter_table('endless_game_stats', schema=None) as batch_op:
        batch_op.drop_column('boomerangsUsed')

    # ### end Alembic commands ###
